name: Run API Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  api-test:
    runs-on: ubuntu-latest
    env:
      TRELLO_BOARD_NAME: 'Test Github board'
      TRELLO_BOARD_DESC: 'Created by API with Postman/Newman in Github actions'

    strategy:
      fail-fast: false
      matrix:
        node-version: [18]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install
        working-directory: api-tests/

      - name: Run Tests
        run: |
          npm run ci -- \
          --env-var "api_key=${{ secrets.TRELLO_API_KEY }}" \
          --env-var "token=${{ secrets.TRELLO_API_TOKEN }}" \
          --env-var "name=${{ env.TRELLO_BOARD_NAME }}" \
          --env-var "description=${{ env.TRELLO_BOARD_DESC }}"
        working-directory: api-tests/